import { VALID_CATEGORIES, CATEGORIES_BY_GROUP, CATEGORY_GROUPS } from '../lib/validation';

// Category slugs mapping
export const CATEGORY_SLUGS: Record<string, string> = {
  'Ecommerce': 'ecommerce',
  'Business Website': 'business_website',
  'Blog Platform': 'blog_platform',
  'Portfolio': 'portfolio',
  'Education Platform': 'education_platform',
  'Newsletter System': 'newsletter_system',
  'Magazine CMS': 'magazine_cms',
  'Social Media App': 'social_media_app',
  'Booking System': 'booking_system',
  'SaaS Platform': 'saas_platform',
  'Landing Page Project': 'landing_page',
  'Web Development': 'web_development',
  'Mobile Development': 'mobile_development',
  'Full Stack Application': 'full_stack',
  'Frontend Project': 'frontend_project',
  'Backend API': 'backend_api',
  'Developer Tools': 'developer_tools',
  'CLI Tools': 'cli_tools',
  'Framework Boilerplate': 'framework_boilerplate',
  'Libraries': 'libraries',
  'Design Systems': 'design_systems',
  'AI Agents': 'ai_agents',
  'Machine Learning': 'machine_learning',
  'Deep Learning': 'deep_learning',
  'Data Science': 'data_science',
  'Automation Systems': 'automation_systems',
  'LLM Integrations': 'llm_integrations',
  'Prompt Engineering': 'prompt_engineering',
  'Model Evaluation': 'model_evaluation',
  'DevOps': 'devops',
  'Infrastructure': 'infrastructure',
  'Cloud Native': 'cloud_native',
  'Docker Projects': 'docker_projects',
  'Kubernetes': 'kubernetes',
  'CI/CD': 'ci_cd',
  'Self Hosted': 'self_hosted',
  'Monitoring Tools': 'monitoring_tools',
  'Cyber Security': 'cyber_security',
  'Ethical Hacking': 'ethical_hacking',
  'Security Research': 'security_research',
  'Encryption Systems': 'encryption_systems',
  'Awesome Lists': 'awesome_lists',
  'Cheat Sheets': 'cheat_sheets',
  'Roadmaps': 'roadmaps',
  'Public APIs': 'public_apis',
  'Interview Preparation': 'interview_prep',
  'Open Source Books': 'open_source_books',
  'Project Based Learning': 'project_based_learning',
  'Curated Resources': 'curated_resources',
  'Web3': 'web3',
  'Blockchain': 'blockchain',
  'Embedded Systems': 'embedded_systems',
  'IoT': 'iot',
  'Low Code Platforms': 'low_code',
  'No Code Platforms': 'no_code',
  'Comparison Repositories': 'comparison_repos',
  'Top 10 Collections': 'top10_collections',
  'Local to Remote Migration': 'local_to_remote',
  'Mirror Repository': 'mirror_repository',
  'Archived Repository': 'archived_repository',
  'Internal Tools': 'internal_tools',
};

// Commit templates - 20+ messages per category
export const COMMIT_TEMPLATES: Record<string, string[]> = {
  // ============ BUSINESS & WEBSITE PROJECTS ============
  
  ecommerce: [
    'feat: implement shopping cart with persistent storage',
    'feat: add product search with filtering and sorting',
    'feat: integrate payment gateway for checkout flow',
    'feat: create product detail page with image gallery',
    'feat: build user authentication and account management',
    'feat: implement order tracking system',
    'feat: add inventory management dashboard',
    'feat: create coupon and discount system',
    'feat: build customer review and rating system',
    'feat: implement wishlist functionality',
    'feat: add related products recommendation engine',
    'feat: create admin panel for product management',
    'fix: resolve payment processing timeout issue',
    'fix: fix cart item quantity validation',
    'fix: correct inventory count synchronization',
    'refactor: optimize product listing query performance',
    'refactor: simplify checkout flow logic',
    'docs: update API documentation for payment integration',
    'chore: update dependencies to latest versions',
    'perf: improve page load time with code splitting',
    'test: add unit tests for cart operations',
    'ci: configure GitHub Actions for CI/CD pipeline',
  ],

  business_website: [
    'feat: implement responsive navigation with mega menu',
    'feat: add contact form with email integration',
    'feat: create about us page with team section',
    'feat: build services showcase with pricing tables',
    'feat: implement FAQ accordion component',
    'feat: add client testimonials carousel',
    'feat: create team member profiles with bio',
    'feat: build location map with Google Maps integration',
    'feat: implement newsletter signup popup',
    'feat: add career page with job application form',
    'fix: resolve mobile menu z-index conflict',
    'fix: fix contact form submission validation',
    'refactor: extract reusable card component',
    'docs: update content management guide',
    'perf: optimize images for web delivery',
    'style: apply brand color system across site',
    'test: add form validation tests',
    'chore: update SEO meta tags',
    'ci: configure sitemap generation',
    'perf: implement lazy loading for images',
    'fix: resolve cross-browser compatibility issues',
  ],

  blog_platform: [
    'feat: implement rich text editor with markdown support',
    'feat: add article categories and tagging system',
    'feat: create featured posts carousel',
    'feat: build related posts recommendation engine',
    'feat: implement social sharing buttons',
    'feat: add reading time estimate indicator',
    'feat: create author profile pages',
    'feat: implement comment system with moderation',
    'feat: add newsletter subscription integration',
    'feat: build search functionality with filters',
    'fix: resolve image upload size limit',
    'fix: fix markdown parsing edge cases',
    'refactor: extract blog post card component',
    'docs: update contributor guidelines',
    'perf: implement pagination with infinite scroll',
    'style: apply typography scale system',
    'test: add markdown rendering tests',
    'chore: update static site generator version',
    'ci: configure RSS feed generation',
    'perf: add caching for热门文章',
    'fix: resolve SEO canonical URL issues',
  ],

  portfolio: [
    'feat: implement project gallery with lightbox',
    'feat: add skill visualization with progress bars',
    'feat: create experience timeline component',
    'feat: build resume download functionality',
    'feat: implement contact form with validation',
    'feat: add project filtering by category',
    'feat: create about me section with bio',
    'feat: build certifications display section',
    'feat: implement dark mode toggle',
    'feat: add social media link integration',
    'fix: resolve masonry layout alignment',
    'fix: fix mobile responsive breakpoints',
    'refactor: extract project card component',
    'docs: update portfolio content guide',
    'perf: optimize portfolio image loading',
    'style: apply consistent spacing system',
    'test: add form submission tests',
    'chore: update dependencies',
    'ci: configure build optimization',
    'perf: implement lazy loading for project images',
    'fix: resolve accessibility keyboard navigation',
  ],

  education_platform: [
    'feat: implement course enrollment system',
    'feat: add video player with progress tracking',
    'feat: create quiz and assessment engine',
    'feat: build student progress dashboard',
    'feat: implement discussion forum',
    'feat: add certificate generation',
    'feat: create instructor management panel',
    'feat: build course curriculum builder',
    'feat: implement assignment submission system',
    'feat: add grade book functionality',
    'fix: resolve video playback buffering issue',
    'fix: fix quiz timer synchronization',
    'refactor: extract lesson card component',
    'docs: update instructor guide',
    'perf: optimize video streaming delivery',
    'style: apply learning-friendly typography',
    'test: add assessment validation tests',
    'chore: update course content',
    'ci: configure SCORM compliance',
    'perf: implement offline viewing capability',
    'fix: resolve progress sync across devices',
  ],

  newsletter_system: [
    'feat: implement subscriber management dashboard',
    'feat: add email template builder',
    'feat: create campaign scheduling system',
    'feat: build email analytics tracking',
    'feat: implement A/B testing for subject lines',
    'feat: add unsubscribe handling',
    'feat: create automation workflows',
    'feat: build subscriber segmentation',
    'feat: implement bounce rate tracking',
    'feat: add click-through analytics',
    'fix: resolve email delivery failures',
    'fix: fix template rendering issues',
    'refactor: extract email service module',
    'docs: update sender policy configuration',
    'perf: optimize email sending throughput',
    'style: apply email design best practices',
    'test: add email template tests',
    'chore: update SPF and DKIM records',
    'ci: configure email delivery monitoring',
    'perf: implement email queue optimization',
    'fix: resolve subscriber sync delays',
  ],

  magazine_cms: [
    'feat: implement article publishing workflow',
    'feat: add editorial calendar system',
    'feat: create issue management interface',
    'feat: build contributor author profiles',
    'feat: implement ad banner management',
    'feat: add print layout export',
    'feat: create content recommendation engine',
    'feat: build subscription management',
    'feat: implement paywall functionality',
    'feat: add multimedia content embedding',
    'fix: resolve content sync issues',
    'fix: fix image asset management',
    'refactor: extract article metadata handler',
    'docs: update editorial guidelines',
    'perf: optimize content delivery CDN',
    'style: apply magazine typography hierarchy',
    'test: add content validation tests',
    'chore: update copyright notices',
    'ci: configure automated content backup',
    'perf: implement article caching',
    'fix: resolve SEO structured data issues',
  ],

  social_media_app: [
    'feat: implement user authentication flow',
    'feat: add post creation with media upload',
    'feat: create news feed algorithm',
    'feat: build user profile pages',
    'feat: implement follow/unfollow system',
    'feat: add like and reaction system',
    'feat: create comment threading',
    'feat: build direct messaging',
    'feat: implement hashtag system',
    'feat: add notification center',
    'fix: resolve post upload timeout',
    'fix: fix feed refresh performance',
    'refactor: extract social graph module',
    'docs: update API rate limiting guide',
    'perf: optimize news feed query',
    'style: apply consistent component library',
    'test: add social interaction tests',
    'chore: update privacy policy',
    'ci: configure content moderation pipeline',
    'perf: implement real-time updates',
    'fix: resolve memory leak in feed',
  ],

  booking_system: [
    'feat: implement availability calendar',
    'feat: add reservation booking flow',
    'feat: create time slot management',
    'feat: build customer management system',
    'feat: implement confirmation emails',
    'feat: add cancellation handling',
    'feat: create payment processing',
    'feat: build booking analytics',
    'feat: implement waitlist functionality',
    'feat: add resource allocation',
    'fix: resolve double booking race condition',
    'fix: fix timezone handling',
    'refactor: extract booking validation module',
    'docs: update integration guide',
    'perf: optimize calendar rendering',
    'style: apply booking UI patterns',
    'test: add booking workflow tests',
    'chore: update business hours',
    'ci: configure automated reminders',
    'perf: implement availability caching',
    'fix: resolve calendar sync issues',
  ],

  saas_platform: [
    'feat: implement multi-tenant architecture',
    'feat: add subscription billing system',
    'feat: create user role management',
    'feat: build usage analytics dashboard',
    'feat: implement onboarding flow',
    'feat: add feature flags system',
    'feat: create API access management',
    'feat: build webhook integrations',
    'feat: implement audit logging',
    'feat: add team collaboration features',
    'fix: resolve data isolation leaks',
    'fix: fix billing calculation errors',
    'refactor: extract tenant context handler',
    'docs: update tenant onboarding guide',
    'perf: optimize multi-tenant queries',
    'style: apply enterprise UI standards',
    'test: add tenant isolation tests',
    'chore: update SLA documentation',
    'ci: configure deployment pipeline',
    'perf: implement connection pooling',
    'fix: resolve session management issues',
  ],

  landing_page: [
    'feat: implement hero section with CTA',
    'feat: add feature highlights section',
    'feat: create pricing comparison table',
    'feat: build testimonial slider',
    'feat: implement lead capture form',
    'feat: add social proof section',
    'feat: create FAQ accordion',
    'feat: build footer with navigation',
    'feat: implement responsive layout',
    'feat: add animation on scroll',
    'fix: resolve mobile layout overflow',
    'fix: fix CTA button contrast',
    'refactor: extract section components',
    'docs: update conversion optimization guide',
    'perf: optimize above-fold rendering',
    'style: apply conversion-focused design',
    'test: add form submission tests',
    'chore: update analytics tracking',
    'ci: configure A/B testing setup',
    'perf: implement lazy loading',
    'fix: resolve accessibility issues',
  ],

  // ============ SOFTWARE DEVELOPMENT ============

  web_development: [
    'feat: implement responsive navbar with mobile hamburger menu',
    'fix: resolve CSS specificity conflict in hero section',
    'refactor: extract reusable Button component',
    'docs: update README with local development setup guide',
    'perf: add lazy loading for below-fold images',
    'test: add unit tests for form validation helpers',
    'style: apply consistent 8px spacing system across components',
    'ci: configure GitHub Actions for lint and build checks',
    'feat: add dark mode toggle with localStorage persistence',
    'fix: correct z-index stacking on modal overlay',
    'chore: upgrade TailwindCSS to v4 and update config',
    'feat: implement infinite scroll for blog post feed',
    'fix: resolve hydration mismatch in SSR-rendered components',
    'refactor: migrate class components to functional with hooks',
    'perf: implement route-based code splitting',
    'feat: add skeleton loader for async content sections',
    'docs: document component API in Storybook',
    'fix: handle empty state in data table gracefully',
    'feat: integrate Google Analytics with custom event tracking',
    'refactor: replace inline styles with Tailwind utility classes',
  ],

  mobile_development: [
    'feat: implement native navigation patterns',
    'feat: add responsive layouts for various screen sizes',
    'feat: create gesture-based interactions',
    'feat: build offline-first data sync',
    'feat: implement push notification handling',
    'feat: add biometric authentication',
    'feat: create camera and media capture',
    'feat: build location-based features',
    'feat: implement app state persistence',
    'feat: add mobile-specific animations',
    'fix: resolve iOS safe area insets',
    'fix: fix Android back button handling',
    'refactor: extract native module bridges',
    'docs: update cross-platform development guide',
    'perf: optimize app startup time',
    'style: apply mobile UI conventions',
    'test: add device-specific tests',
    'chore: update app icons and splash screens',
    'ci: configure mobile CI pipeline',
    'perf: implement lazy module loading',
    'fix: resolve memory pressure handling',
  ],

  full_stack: [
    'feat: implement user authentication system',
    'feat: add RESTful API endpoints',
    'feat: create database schema with migrations',
    'feat: build real-time WebSocket connections',
    'feat: implement file upload handling',
    'feat: add email notification service',
    'feat: create admin dashboard',
    'feat: build API documentation',
    'feat: implement caching layer',
    'feat: add background job processing',
    'fix: resolve N+1 query problems',
    'fix: fix session token expiration',
    'refactor: extract service layer architecture',
    'docs: update API versioning strategy',
    'perf: optimize database query performance',
    'style: apply consistent code structure',
    'test: add integration tests for API',
    'chore: update environment configuration',
    'ci: configure full stack CI/CD',
    'perf: implement request rate limiting',
    'fix: resolve CORS configuration issues',
  ],

  frontend_project: [
    'feat: implement component library',
    'feat: add state management system',
    'feat: create reusable UI components',
    'feat: build responsive design system',
    'feat: implement internationalization',
    'feat: add accessibility improvements',
    'feat: create form validation library',
    'feat: build data visualization charts',
    'feat: implement virtual scrolling',
    'feat: add error boundary handling',
    'fix: resolve bundle size bloat',
    'fix: fix re-rendering performance',
    'refactor: extract custom hooks',
    'docs: update component documentation',
    'perf: implement code splitting',
    'style: apply design tokens',
    'test: add component snapshot tests',
    'chore: update build configuration',
    'ci: configure visual regression testing',
    'perf: optimize critical rendering path',
    'fix: resolve TypeScript strict mode errors',
  ],

  backend_api: [
    'feat: implement RESTful endpoints',
    'feat: add GraphQL API schema',
    'feat: create authentication middleware',
    'feat: build rate limiting system',
    'feat: implement request validation',
    'feat: add response caching',
    'feat: create API versioning',
    'feat: build webhook handlers',
    'feat: implement pagination',
    'feat: add error handling middleware',
    'fix: resolve memory leak in connection pool',
    'fix: fix request timeout handling',
    'refactor: extract controller logic',
    'docs: update OpenAPI specification',
    'perf: optimize database query execution',
    'style: apply API design best practices',
    'test: add API endpoint tests',
    'chore: update dependency versions',
    'ci: configure API load testing',
    'perf: implement connection pooling',
    'fix: resolve circular dependency issues',
  ],

  developer_tools: [
    'feat: implement CLI interface',
    'feat: add configuration management',
    'feat: create progress indicators',
    'feat: build interactive prompts',
    'feat: implement file system operations',
    'feat: add package publishing',
    'feat: create documentation generator',
    'feat: build testing utilities',
    'feat: implement code generation',
    'feat: add debugging tools',
    'fix: resolve cross-platform path issues',
    'fix: fix output formatting inconsistencies',
    'refactor: extract command handlers',
    'docs: update CLI usage guide',
    'perf: optimize command execution',
    'style: apply CLI output standards',
    'test: add CLI argument parsing tests',
    'chore: update version number',
    'ci: configure release automation',
    'perf: implement parallel execution',
    'fix: resolve async operation handling',
  ],

  cli_tools: [
    'feat: implement command-line argument parser',
    'feat: add colored output support',
    'feat: create progress bar component',
    'feat: build interactive menu system',
    'feat: implement file glob patterns',
    'feat: add configuration file handling',
    'feat: create auto-completion scripts',
    'feat: build environment variable support',
    'feat: implement version checking',
    'feat: add update notifier',
    'fix: resolve ANSI escape code handling',
    'fix: fix terminal width detection',
    'refactor: extract CLI framework module',
    'docs: update command reference',
    'perf: optimize startup time',
    'style: apply POSIX CLI conventions',
    'test: add integration tests',
    'chore: update man page documentation',
    'ci: configure cross-platform builds',
    'perf: implement lazy loading',
    'fix: resolve Unicode display issues',
  ],

  framework_boilerplate: [
    'feat: implement starter project template',
    'feat: add development server configuration',
    'feat: create build optimization setup',
    'feat: build testing framework integration',
    'feat: implement hot module replacement',
    'feat: add TypeScript configuration',
    'feat: create linting ruleset',
    'feat: build CI/CD configuration',
    'feat: implement environment configs',
    'feat: add code generation scripts',
    'fix: resolve build configuration conflicts',
    'fix: fix hot reload not working',
    'refactor: extract configuration modules',
    'docs: update getting started guide',
    'perf: optimize build speed',
    'style: apply project structure conventions',
    'test: add template validation tests',
    'chore: update framework dependencies',
    'ci: configure automated releases',
    'perf: implement incremental builds',
    'fix: resolve path alias issues',
  ],

  libraries: [
    'feat: implement core library functionality',
    'feat: add public API surface',
    'feat: create TypeScript definitions',
    'feat: build documentation with examples',
    'feat: implement tree-shaking support',
    'feat: add bundle size optimization',
    'feat: create unit test suite',
    'feat: build browser compatibility',
    'feat: implement ESM and CJS exports',
    'feat: add semver versioning',
    'fix: resolve circular dependency',
    'fix: fix type definition errors',
    'refactor: extract internal modules',
    'docs: update API reference',
    'perf: optimize bundle output',
    'style: apply library naming conventions',
    'test: add public API tests',
    'chore: update changelog',
    'ci: configure npm publishing',
    'perf: implement lazy evaluation',
    'fix: resolve side effect handling',
  ],

  design_systems: [
    'feat: implement design tokens',
    'feat: add component library foundation',
    'feat: create typography scale',
    'feat: build color palette system',
    'feat: implement spacing and layout',
    'feat: add icon library integration',
    'feat: create form component patterns',
    'feat: build navigation components',
    'feat: implement modal and overlay patterns',
    'feat: add accessibility standards',
    'fix: resolve component prop conflicts',
    'fix: fix accessibility violations',
    'refactor: extract primitive components',
    'docs: update component guidelines',
    'perf: optimize bundle size',
    'style: apply design principles',
    'test: add visual regression tests',
    'chore: update storybook configuration',
    'ci: configure design token generation',
    'perf: implement component lazy loading',
    'fix: resolve theme switching issues',
  ],

  // ============ AI & DATA ============

  ai_agents: [
    'feat: implement agent orchestration layer',
    'feat: add task decomposition engine',
    'feat: create memory management system',
    'feat: build tool use framework',
    'feat: implement planning algorithms',
    'feat: add reflection mechanism',
    'feat: create multi-agent communication',
    'feat: build context injection',
    'feat: implement prompt templates',
    'feat: add agent monitoring',
    'fix: fix token limit handling',
    'fix: resolve tool execution errors',
    'refactor: extract agent base class',
    'docs: add agent architecture guide',
    'perf: optimize API call batching',
    'style: standardize error messages',
    'test: add agent behavior tests',
    'chore: update model versions',
    'ci: configure evaluation pipeline',
    'security: add input sanitization',
  ],

  machine_learning: [
    'feat: implement data preprocessing pipeline',
    'feat: add model training loop',
    'feat: create evaluation metrics',
    'feat: build hyperparameter tuning',
    'feat: implement cross-validation',
    'feat: add model serialization',
    'feat: create prediction serving',
    'feat: build feature engineering',
    'feat: implement model versioning',
    'feat: add experiment tracking',
    'fix: fix gradient computation',
    'fix: resolve overfitting issues',
    'refactor: extract training utilities',
    'docs: add model documentation',
    'perf: optimize GPU utilization',
    'style: apply ML coding standards',
    'test: add model validation tests',
    'chore: update ML framework versions',
    'ci: configure model registry',
    'perf: improve inference speed',
  ],

  deep_learning: [
    'feat: implement neural network architecture',
    'feat: add convolutional layers',
    'feat: create recurrent modules',
    'feat: build attention mechanisms',
    'feat: implement transformer blocks',
    'feat: add loss functions',
    'feat: create optimizer implementations',
    'feat: build gradient clipping',
    'feat: implement batch normalization',
    'feat: add dropout regularization',
    'fix: fix gradient vanishing',
    'fix: resolve exploding gradients',
    'refactor: extract layer components',
    'docs: add architecture documentation',
    'perf: optimize CUDA kernel usage',
    'style: apply DL naming conventions',
    'test: add layer unit tests',
    'chore: update framework versions',
    'ci: configure GPU cluster training',
    'perf: implement mixed precision training',
    'fix: resolve memory fragmentation',
  ],

  data_science: [
    'feat: implement exploratory data analysis',
    'feat: add data cleaning pipelines',
    'feat: create statistical analysis',
    'feat: build data visualization',
    'feat: implement feature engineering',
    'feat: add correlation analysis',
    'feat: create data transformation',
    'feat: build outlier detection',
    'feat: implement imputation strategies',
    'feat: add dimensionality reduction',
    'fix: resolve missing data patterns',
    'fix: fix data type conversions',
    'refactor: extract analysis utilities',
    'docs: update data dictionary',
    'perf: optimize pandas operations',
    'style: apply data science conventions',
    'test: add statistical tests',
    'chore: update dataset versions',
    'ci: configure data validation',
    'perf: implement parallel processing',
    'fix: resolve memory errors',
  ],

  automation_systems: [
    'feat: implement workflow automation',
    'feat: add task scheduling system',
    'feat: create event-driven triggers',
    'feat: build condition evaluation',
    'feat: implement retry mechanisms',
    'feat: add notification system',
    'feat: create audit logging',
    'feat: build error handling',
    'feat: implement state management',
    'feat: add distributed execution',
    'fix: resolve scheduling conflicts',
    'fix: fix task timeout handling',
    'refactor: extract automation engine',
    'docs: update automation guide',
    'perf: optimize execution time',
    'style: apply workflow conventions',
    'test: add automation tests',
    'chore: update cron expressions',
    'ci: configure monitoring alerts',
    'perf: implement parallel tasks',
    'fix: resolve deadlock conditions',
  ],

  llm_integrations: [
    'feat: implement OpenAI API client',
    'feat: add Anthropic integration',
    'feat: create model abstraction layer',
    'feat: build prompt engineering tools',
    'feat: implement response parsing',
    'feat: add token counting',
    'feat: create streaming responses',
    'feat: build retry logic',
    'feat: implement cost tracking',
    'feat: add fallback models',
    'fix: resolve API timeout issues',
    'fix: fix rate limit handling',
    'refactor: extract provider adapters',
    'docs: update integration guide',
    'perf: optimize API calls',
    'style: apply API conventions',
    'test: add integration tests',
    'chore: update API versions',
    'ci: configure usage monitoring',
    'perf: implement caching layer',
    'fix: resolve context window limits',
  ],

  prompt_engineering: [
    'feat: implement prompt templates',
    'feat: add prompt testing framework',
    'feat: create evaluation metrics',
    'feat: build prompt versioning',
    'feat: implement few-shot learning',
    'feat: add chain-of-thought prompts',
    'feat: create role-based prompts',
    'feat: build prompt optimization',
    'feat: implement context injection',
    'feat: add prompt security',
    'fix: resolve prompt injection',
    'fix: fix output parsing errors',
    'refactor: extract prompt utilities',
    'docs: update best practices guide',
    'perf: optimize token usage',
    'style: apply prompt conventions',
    'test: add prompt validation tests',
    'chore: update template library',
    'ci: configure prompt testing',
    'perf: implement prompt caching',
    'fix: resolve encoding issues',
  ],

  model_evaluation: [
    'feat: implement evaluation metrics',
    'feat: add benchmark datasets',
    'feat: create comparison framework',
    'feat: build performance profiling',
    'feat: implement human evaluation',
    'feat: add automated scoring',
    'feat: create bias detection',
    'feat: build fairness metrics',
    'feat: implement robustness testing',
    'feat: add regression testing',
    'fix: resolve metric calculation errors',
    'fix: fix benchmark inconsistencies',
    'refactor: extract evaluation utils',
    'docs: update evaluation protocol',
    'perf: optimize evaluation speed',
    'style: apply evaluation standards',
    'test: add metric validation tests',
    'chore: update benchmark versions',
    'ci: configure automated evaluation',
    'perf: implement parallel evaluation',
    'fix: resolve data leakage issues',
  ],

  // ============ DEVOPS & INFRASTRUCTURE ============

  devops: [
    'feat: implement CI/CD pipeline',
    'feat: add infrastructure provisioning',
    'feat: create deployment automation',
    'feat: build monitoring integration',
    'feat: implement container orchestration',
    'feat: add secret management',
    'feat: create backup system',
    'feat: build disaster recovery',
    'feat: implement log aggregation',
    'feat: add alerting system',
    'fix: resolve deployment failures',
    'fix: fix environment configuration',
    'refactor: extract deployment scripts',
    'docs: update runbook documentation',
    'perf: optimize pipeline execution',
    'style: apply DevOps conventions',
    'test: add deployment tests',
    'chore: update infrastructure code',
    'ci: configure automated testing',
    'perf: implement parallel jobs',
    'fix: resolve resource limits',
  ],

  infrastructure: [
    'feat: implement infrastructure as code',
    'feat: add cloud resource provisioning',
    'feat: create network configuration',
    'feat: build security groups',
    'feat: implement load balancers',
    'feat: add auto-scaling policies',
    'feat: create database setup',
    'feat: build cache configuration',
    'feat: implement DNS management',
    'feat: add CDN configuration',
    'fix: resolve resource conflicts',
    'fix: fix networking issues',
    'refactor: extract Terraform modules',
    'docs: update infrastructure guide',
    'perf: optimize provisioning speed',
    'style: apply IaC conventions',
    'test: add infrastructure tests',
    'chore: update resource tags',
    'ci: configure drift detection',
    'perf: implement state management',
    'fix: resolve circular dependencies',
  ],

  cloud_native: [
    'feat: implement Kubernetes manifests',
    'feat: add service mesh configuration',
    'feat: create Helm charts',
    'feat: build pod autoscaling',
    'feat: implement ingress controllers',
    'feat: add service discovery',
    'feat: create configMaps and secrets',
    'feat: build persistent volumes',
    'feat: implement network policies',
    'feat: add resource quotas',
    'fix: resolve pod crash loops',
    'fix: fix image pull errors',
    'refactor: extract K8s utilities',
    'docs: update deployment guide',
    'perf: optimize resource usage',
    'style: apply K8s conventions',
    'test: add K8s integration tests',
    'chore: update helm dependencies',
    'ci: configure GitOps workflow',
    'perf: implement pod scheduling',
    'fix: resolve storage class issues',
  ],

  docker_projects: [
    'feat: implement Dockerfile optimization',
    'feat: add multi-stage builds',
    'feat: create docker-compose setup',
    'feat: build development environment',
    'feat: implement production images',
    'feat: add health checks',
    'feat: create volume mounting',
    'feat: build networking configuration',
    'feat: implement image scanning',
    'feat: add CI integration',
    'fix: resolve build context issues',
    'fix: fix layer caching',
    'refactor: extract docker utilities',
    'docs: update docker best practices',
    'perf: optimize image size',
    'style: apply docker conventions',
    'test: add container tests',
    'chore: update base images',
    'ci: configure buildx builds',
    'perf: implement build parallelization',
    'fix: resolve port conflicts',
  ],

  kubernetes: [
    'feat: implement deployment manifests',
    'feat: add statefulset configurations',
    'feat: create daemonset for agents',
    'feat: build custom resources',
    'feat: implement operators',
    'feat: add ingress routing',
    'feat: create service accounts',
    'feat: build RBAC policies',
    'feat: implement helm deployments',
    'feat: add Kustomize overlays',
    'fix: resolve pod scheduling issues',
    'fix: fix service endpoint errors',
    'refactor: extract k8s templates',
    'docs: update K8s operations guide',
    'perf: optimize cluster resources',
    'style: apply K8s naming conventions',
    'test: add K8s manifests tests',
    'chore: update k8s version',
    'ci: configure cluster management',
    'perf: implement pod disruption budgets',
    'fix: resolve volume mount issues',
  ],

  ci_cd: [
    'feat: implement pipeline stages',
    'feat: add build automation',
    'feat: create test execution',
    'feat: build artifact publishing',
    'feat: implement deployment triggers',
    'feat: add branch protection',
    'feat: create pull request checks',
    'feat: build release automation',
    'feat: implement rollback mechanism',
    'feat: add pipeline templates',
    'fix: resolve build cache issues',
    'fix: fix test flakiness',
    'refactor: extract pipeline library',
    'docs: update CI configuration guide',
    'perf: optimize build parallelization',
    'style: apply CI conventions',
    'test: add pipeline validation',
    'chore: update runner versions',
    'ci: configure self-hosted runners',
    'perf: implement artifact caching',
    'fix: resolve secret injection',
  ],

  self_hosted: [
    'feat: implement self-hosted deployment',
    'feat: add reverse proxy setup',
    'feat: create SSL certificate management',
    'feat: build authentication system',
    'feat: implement data backup',
    'feat: add monitoring stack',
    'feat: create log management',
    'feat: build update automation',
    'feat: implement resource limits',
    'feat: add security hardening',
    'fix: resolve proxy configuration',
    'fix: fix certificate renewal',
    'refactor: extract setup scripts',
    'docs: update self-hosting guide',
    'perf: optimize resource allocation',
    'style: apply self-hosted conventions',
    'test: add installation tests',
    'chore: update version compatibility',
    'ci: configure automated updates',
    'perf: implement health checks',
    'fix: resolve database connection issues',
  ],

  monitoring_tools: [
    'feat: implement metrics collection',
    'feat: add log aggregation',
    'feat: create alerting rules',
    'feat: build dashboard visualizations',
    'feat: implement trace sampling',
    'feat: add performance profiling',
    'feat: create uptime monitoring',
    'feat: build anomaly detection',
    'feat: implement incident management',
    'feat: add reporting system',
    'fix: resolve metric collection gaps',
    'fix: fix alert noise',
    'refactor: extract monitoring utils',
    'docs: update monitoring setup guide',
    'perf: optimize data ingestion',
    'style: apply monitoring conventions',
    'test: add alert validation tests',
    'chore: update alert thresholds',
    'ci: configure health endpoints',
    'perf: implement downsampling',
    'fix: resolve storage issues',
  ],

  // ============ SECURITY ============

  cyber_security: [
    'feat: implement security scanning',
    'feat: add vulnerability detection',
    'feat: create penetration testing',
    'feat: build threat modeling',
    'feat: implement security audit',
    'feat: add incident response',
    'feat: create security dashboard',
    'feat: build compliance checking',
    'feat: implement access control',
    'feat: add security training',
    'fix: fix vulnerability findings',
    'fix: resolve security gaps',
    'refactor: extract security utils',
    'docs: add security guide',
    'perf: optimize scanning speed',
    'style: apply security standards',
    'test: add security tests',
    'chore: update security tools',
    'ci: configure security scans',
    'security: add threat intelligence',
  ],

  ethical_hacking: [
    'feat: implement vulnerability scanner',
    'feat: add penetration testing tools',
    'feat: create exploit framework',
    'feat: build reconnaissance automation',
    'feat: implement privilege escalation',
    'feat: add post-exploitation scripts',
    'feat: create red team operations',
    'feat: build social engineering',
    'feat: implement network assessment',
    'feat: add web application testing',
    'fix: resolve tool compatibility',
    'fix: fix false positives',
    'refactor: extract hacking toolkit',
    'docs: update engagement rules',
    'perf: optimize scan efficiency',
    'style: apply professional standards',
    'test: add tool validation',
    'chore: update tool versions',
    'ci: configure secure reporting',
    'perf: implement parallel scanning',
    'fix: resolve detection bypass',
  ],

  security_research: [
    'feat: implement malware analysis',
    'feat: add reverse engineering tools',
    'feat: create vulnerability research',
    'feat: build exploit development',
    'feat: implement cryptographic analysis',
    'feat: add protocol security',
    'feat: create fuzzing framework',
    'feat: build code review automation',
    'feat: implement threat intelligence',
    'feat: add security metrics',
    'fix: resolve analysis tool errors',
    'fix: fix sandbox detection',
    'refactor: extract research utilities',
    'docs: update research methodology',
    'perf: optimize analysis speed',
    'style: apply research standards',
    'test: add validation tests',
    'chore: update CVE database',
    'ci: configure responsible disclosure',
    'perf: implement automation',
    'fix: resolve artifact handling',
  ],

  encryption_systems: [
    'feat: implement encryption algorithms',
    'feat: add key management system',
    'feat: create digital signatures',
    'feat: build hash functions',
    'feat: implement secure communication',
    'feat: add certificate handling',
    'feat: create key exchange protocols',
    'feat: build secure storage',
    'feat: implement zero-knowledge proofs',
    'feat: add homomorphic encryption',
    'fix: resolve key rotation issues',
    'fix: fix padding oracle attacks',
    'refactor: extract crypto library',
    'docs: update cryptographic guide',
    'perf: optimize encryption speed',
    'style: apply crypto standards',
    'test: add cryptographic tests',
    'chore: update algorithm versions',
    'ci: configure compliance checking',
    'perf: implement hardware acceleration',
    'fix: resolve side channel attacks',
  ],

  // ============ KNOWLEDGE & CURATION ============

  awesome_lists: [
    'feat: add new category section',
    'feat: create awesome-list structure',
    'feat: build README template',
    'feat: add contribution guidelines',
    'feat: implement resource linking',
    'feat: add curation workflow',
    'feat: create review process',
    'feat: build categorization system',
    'feat: implement quality checks',
    'feat: add update automation',
    'fix: fix broken links',
    'fix: resolve formatting issues',
    'refactor: extract list templates',
    'docs: add curation guide',
    'perf: optimize link checking',
    'style: apply list conventions',
    'test: add validation tests',
    'chore: update categories',
    'ci: configure link validation',
    'perf: improve readability',
  ],

  cheat_sheets: [
    'feat: implement quick reference format',
    'feat: add command syntax examples',
    'feat: create keyboard shortcuts',
    'feat: build common patterns',
    'feat: implement code snippets',
    'feat: add configuration examples',
    'feat: create troubleshooting tips',
    'feat: build best practices',
    'feat: implement comparison charts',
    'feat: add visual diagrams',
    'fix: resolve format inconsistencies',
    'fix: fix outdated examples',
    'refactor: extract template system',
    'docs: update contribution guide',
    'perf: optimize rendering',
    'style: apply cheat sheet layout',
    'test: add syntax validation',
    'chore: update content versions',
    'ci: configure automated checks',
    'perf: implement search indexing',
    'fix: resolve print styling issues',
  ],

  roadmaps: [
    'feat: implement learning path structure',
    'feat: add skill progression levels',
    'feat: create milestone markers',
    'feat: build resource linking',
    'feat: implement time estimates',
    'feat: add prerequisite mapping',
    'feat: create career tracks',
    'feat: build role-based paths',
    'feat: implement progress tracking',
    'feat: add community contributions',
    'fix: resolve content gaps',
    'fix: fix outdated resources',
    'refactor: extract roadmap engine',
    'docs: update roadmap methodology',
    'perf: optimize rendering speed',
    'style: apply visual hierarchy',
    'test: add path validation',
    'chore: update technology versions',
    'ci: configure content validation',
    'perf: implement interactive features',
    'fix: resolve navigation issues',
  ],

  public_apis: [
    'feat: implement API directory structure',
    'feat: add API documentation format',
    'feat: create endpoint examples',
    'feat: build authentication guides',
    'feat: implement rate limit info',
    'feat: add pricing tiers',
    'feat: create SDK availability',
    'feat: build popularity metrics',
    'feat: implement category sorting',
    'feat: add search functionality',
    'fix: resolve broken endpoints',
    'fix: fix authentication examples',
    'refactor: extract API parser',
    'docs: update submission guidelines',
    'perf: optimize search speed',
    'style: apply API catalog standards',
    'test: add endpoint validation',
    'chore: update API status',
    'ci: configure health checks',
    'perf: implement caching',
    'fix: resolve rate limit data',
  ],

  interview_prep: [
    'feat: implement coding challenge format',
    'feat: add system design questions',
    'feat: create behavioral questions',
    'feat: build answer frameworks',
    'feat: implement time management',
    'feat: add company-specific prep',
    'feat: create mock interview',
    'feat: build progress tracking',
    'feat: implement difficulty levels',
    'feat: add solution explanations',
    'fix: resolve solution accuracy',
    'fix: fix outdated content',
    'refactor: extract question bank',
    'docs: update preparation guide',
    'perf: optimize loading speed',
    'style: apply interview format',
    'test: add solution validation',
    'chore: update question database',
    'ci: configure content validation',
    'perf: implement filtering',
    'fix: resolve accessibility issues',
  ],

  open_source_books: [
    'feat: implement book catalog',
    'feat: add chapter navigation',
    'feat: create reading progress',
    'feat: build search functionality',
    'feat: implement bookmarking',
    'feat: add annotation system',
    'feat: create offline reading',
    'feat: build PDF export',
    'feat: implement multi-format support',
    'feat: add community notes',
    'fix: resolve format issues',
    'fix: fix broken links',
    'refactor: extract reader engine',
    'docs: update contribution guide',
    'perf: optimize rendering',
    'style: apply book formatting',
    'test: add format validation',
    'chore: update book versions',
    'ci: configure build pipeline',
    'perf: implement lazy loading',
    'fix: resolve download issues',
  ],

  project_based_learning: [
    'feat: implement project structure',
    'feat: add step-by-step guide',
    'feat: create code examples',
    'feat: build learning objectives',
    'feat: implement difficulty levels',
    'feat: add prerequisite setup',
    'feat: create milestone checkpoints',
    'feat: build solution code',
    'feat: implement challenge mode',
    'feat: add peer review system',
    'fix: resolve code errors',
    'fix: fix setup instructions',
    'refactor: extract project templates',
    'docs: update learning path',
    'perf: optimize code highlighting',
    'style: apply tutorial format',
    'test: add validation checks',
    'chore: update dependencies',
    'ci: configure code validation',
    'perf: implement offline mode',
    'fix: resolve environment issues',
  ],

  curated_resources: [
    'feat: implement resource collection',
    'feat: add categorization system',
    'feat: create quality rating',
    'feat: build search and filter',
    'feat: implement voting system',
    'feat: add user collections',
    'feat: create curation workflow',
    'feat: build recommendation engine',
    'feat: implement sharing features',
    'feat: add trending resources',
    'fix: resolve broken links',
    'fix: fix categorization',
    'refactor: extract resource manager',
    'docs: update curation criteria',
    'perf: optimize search speed',
    'style: apply resource layout',
    'test: add link validation',
    'chore: update content freshness',
    'ci: configure automated checks',
    'perf: implement caching',
    'fix: resolve duplicate entries',
  ],

  // ============ EMERGING TECH ============

  web3: [
    'feat: implement wallet connection',
    'feat: add smart contract integration',
    'feat: create NFT functionality',
    'feat: build token transfers',
    'feat: implement blockchain queries',
    'feat: add gas optimization',
    'feat: create decentralized storage',
    'feat: build DAO governance',
    'feat: implement oracle integration',
    'feat: add layer 2 support',
    'fix: fix transaction failures',
    'fix: resolve wallet issues',
    'refactor: extract blockchain utils',
    'docs: add Web3 guide',
    'perf: optimize gas usage',
    'style: apply Web3 standards',
    'test: add contract tests',
    'chore: update ABI versions',
    'ci: configure testnets',
    'security: add audit checks',
  ],

  blockchain: [
    'feat: implement consensus mechanism',
    'feat: add transaction pool',
    'feat: create block validation',
    'feat: build p2p networking',
    'feat: implement smart contracts',
    'feat: add mining algorithm',
    'feat: create wallet integration',
    'feat: build state management',
    'feat: implement fork handling',
    'feat: add privacy features',
    'fix: resolve chain reorganization',
    'fix: fix double spend detection',
    'refactor: extract core protocol',
    'docs: update protocol specification',
    'perf: optimize block propagation',
    'style: apply blockchain conventions',
    'test: add consensus tests',
    'chore: update network parameters',
    'ci: configure testnet deployment',
    'perf: implement sharding',
    'fix: resolve gas limit issues',
  ],

  embedded_systems: [
    'feat: implement firmware development',
    'feat: add hardware abstraction',
    'feat: create driver development',
    'feat: build RTOS integration',
    'feat: implement low-power modes',
    'feat: add interrupt handling',
    'feat: create peripheral drivers',
    'feat: build debugging tools',
    'feat: implement OTA updates',
    'feat: add sensor integration',
    'fix: resolve memory constraints',
    'fix: fix timing issues',
    'refactor: extract hardware modules',
    'docs: update firmware guide',
    'perf: optimize code size',
    'style: apply embedded conventions',
    'test: add hardware tests',
    'chore: update toolchain',
    'ci: configure cross-compilation',
    'perf: implement DMA transfers',
    'fix: resolve peripheral conflicts',
  ],

  iot: [
    'feat: implement device connectivity',
    'feat: add MQTT protocol',
    'feat: create sensor data collection',
    'feat: build gateway configuration',
    'feat: implement edge computing',
    'feat: add device provisioning',
    'feat: create data visualization',
    'feat: build alerting system',
    'feat: implement firmware updates',
    'feat: add security certificates',
    'fix: resolve connection drops',
    'fix: fix data synchronization',
    'refactor: extract IoT platform',
    'docs: update device guide',
    'perf: optimize network bandwidth',
    'style: apply IoT conventions',
    'test: add device simulation',
    'chore: update firmware versions',
    'ci: configure OTA pipeline',
    'perf: implement batch processing',
    'fix: resolve protocol translation',
  ],

  low_code: [
    'feat: implement visual builder',
    'feat: add drag-and-drop interface',
    'feat: create component library',
    'feat: build workflow automation',
    'feat: implement data binding',
    'feat: add form builder',
    'feat: create integration connectors',
    'feat: build dashboard designer',
    'feat: implement mobile preview',
    'feat: add version control',
    'fix: resolve component conflicts',
    'fix: fix rendering issues',
    'refactor: extract builder engine',
    'docs: update platform guide',
    'perf: optimize build time',
    'style: apply visual design',
    'test: add component tests',
    'chore: update component library',
    'ci: configure export pipeline',
    'perf: implement incremental builds',
    'fix: resolve undo/redo issues',
  ],

  no_code: [
    'feat: implement visual workflow',
    'feat: add spreadsheet-like interface',
    'feat: create automation rules',
    'feat: build template library',
    'feat: implement user management',
    'feat: add database integration',
    'feat: create email notifications',
    'feat: build API connectors',
    'feat: implement webhook triggers',
    'feat: add mobile app generation',
    'fix: resolve logic errors',
    'fix: fix data type conversion',
    'refactor: extract execution engine',
    'docs: update platform documentation',
    'perf: optimize execution speed',
    'style: apply no-code conventions',
    'test: add logic validation',
    'chore: update template catalog',
    'ci: configure deployment',
    'perf: implement caching',
    'fix: resolve integration failures',
  ],

  comparison_repositories: [
    'feat: implement comparison framework',
    'feat: add feature matrix',
    'feat: create benchmark tests',
    'feat: build criteria weighting',
    'feat: implement scoring system',
    'feat: add user reviews',
    'feat: create pricing comparison',
    'feat: build pros/cons lists',
    'feat: implement recommendation engine',
    'feat: add comparison charts',
    'fix: resolve outdated information',
    'fix: fix data accuracy',
    'refactor: extract comparison engine',
    'docs: update methodology guide',
    'perf: optimize comparison speed',
    'style: apply comparison layout',
    'test: add data validation',
    'chore: update data sources',
    'ci: configure automated updates',
    'perf: implement caching',
    'fix: resolve scoring issues',
  ],

  top10_collections: [
    'feat: implement ranking algorithm',
    'feat: add voting system',
    'feat: create nomination process',
    'feat: build review aggregation',
    'feat: implement criteria scoring',
    'feat: add category organization',
    'feat: create detail pages',
    'feat: build voting analytics',
    'feat: implement seasonal updates',
    'feat: add expert reviews',
    'fix: resolve ranking disputes',
    'fix: fix vote manipulation',
    'refactor: extract ranking engine',
    'docs: update selection criteria',
    'perf: optimize voting speed',
    'style: apply top-list format',
    'test: add ranking validation',
    'chore: update collection schedule',
    'ci: configure vote verification',
    'perf: implement real-time updates',
    'fix: resolve tie-breaking',
  ],

  // ============ REPOSITORY TYPES ============

  local_to_remote: [
    'feat: initialize local repository',
    'feat: add remote origin',
    'feat: create initial commit',
    'feat: push all branches',
    'feat: configure branch tracking',
    'feat: add CI/CD configuration',
    'feat: create README from local',
    'feat: setup collaboration',
    'feat: implement remote sync',
    'feat: add backup strategy',
    'fix: fix remote URL issues',
    'fix: resolve branch conflicts',
    'refactor: extract migration script',
    'docs: add migration guide',
    'perf: optimize push operations',
    'style: apply repo standards',
    'test: add migration tests',
    'chore: update remote config',
    'ci: configure automation',
    'security: add remote validation',
  ],

  mirror_repository: [
    'feat: create bare repository',
    'feat: add remote mirroring',
    'feat: implement clone synchronization',
    'feat: build fetch automation',
    'feat: implement push mirroring',
    'feat: add branch filtering',
    'feat: create backup system',
    'feat: build sync scheduling',
    'feat: implement refspec mapping',
    'feat: add hook scripts',
    'fix: resolve sync conflicts',
    'fix: fix bandwidth issues',
    'refactor: extract mirror utilities',
    'docs: update mirror guide',
    'perf: optimize transfer speed',
    'style: apply mirror conventions',
    'test: add sync validation',
    'chore: update schedule',
    'ci: configure monitoring',
    'perf: implement compression',
    'fix: resolve authentication issues',
  ],

  archived_repository: [
    'feat: implement repository archival',
    'feat: add metadata preservation',
    'feat: create archive manifest',
    'feat: build storage optimization',
    'feat: implement access controls',
    'feat: add documentation snapshot',
    'feat: create reference links',
    'feat: build search indexing',
    'feat: implement retrieval system',
    'feat: add preservation metadata',
    'fix: resolve data integrity',
    'fix: fix missing files',
    'refactor: extract archive tools',
    'docs: update archival policy',
    'perf: optimize storage',
    'style: apply archive standards',
    'test: add integrity checks',
    'chore: update retention policy',
    'ci: configure verification',
    'perf: implement compression',
    'fix: resolve format issues',
  ],

  internal_tools: [
    'feat: implement admin dashboard',
    'feat: add user management',
    'feat: create system configuration',
    'feat: build audit logging',
    'feat: implement access control',
    'feat: add notification system',
    'feat: create data export',
    'feat: build automation scripts',
    'feat: implement batch processing',
    'feat: add monitoring integration',
    'fix: resolve permission issues',
    'fix: fix data display errors',
    'refactor: extract admin modules',
    'docs: update admin guide',
    'perf: optimize query performance',
    'style: apply internal UI',
    'test: add admin tests',
    'chore: update configuration',
    'ci: configure deployment',
    'perf: implement caching',
    'fix: resolve session issues',
  ],
};

// Generate fallback templates for categories not explicitly defined
VALID_CATEGORIES.forEach(category => {
  if (!COMMIT_TEMPLATES[CATEGORY_SLUGS[category]]) {
    COMMIT_TEMPLATES[CATEGORY_SLUGS[category]] = COMMIT_TEMPLATES['web_development'];
  }
});

/**
 * Fisher-Yates shuffle algorithm
 */
export function shuffleArray<T>(array: T[]): T[] {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

/**
 * Message rotation engine for commit messages
 */
export class MessageRotationEngine {
  private messages: string[];
  private index: number = 0;
  private reshuffled: boolean = false;

  constructor(categorySlug: string) {
    const templates = COMMIT_TEMPLATES[categorySlug] ?? COMMIT_TEMPLATES['web_development'];
    this.messages = shuffleArray([...templates]);
  }

  getNextMessage(): string {
    if (this.index >= this.messages.length) {
      this.messages = shuffleArray([...this.messages]);
      this.index = 0;
      this.reshuffled = true;
    }
    return this.messages[this.index++];
  }

  getMessages(count: number): string[] {
    return Array.from({ length: count }, () => this.getNextMessage());
  }

  reset(): void {
    this.index = 0;
    this.reshuffled = false;
  }

  wasReshuffled(): boolean {
    return this.reshuffled;
  }
}

/**
 * Get commit messages for a category
 */
export function getCommitMessages(category: string, count: number): string[] {
  const slug = CATEGORY_SLUGS[category] ?? 'web_development';
  const engine = new MessageRotationEngine(slug);
  return engine.getMessages(count);
}

/**
 * Generate file content with commit messages
 */
export function generateFileContent(existingContent: string, message: string, index: number): string {
  const timestamp = new Date().toISOString();
  const newEntry = `\n---\nCommit ${index}: ${message}\nTimestamp: ${timestamp}\n`;
  return existingContent + newEntry;
}

/**
 * Generate initial file content
 */
export function generateInitialContent(): string {
  const timestamp = new Date().toISOString();
  return `# Educational Commit Log\n\nInitialized: ${timestamp}\n`;
}
